# ---------------------------------------------------------------------------
# "PeerOrgs" - Định nghĩa tổ chức ECommercePlatformOrg (Sàn TMĐT)
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: ECommercePlatformOrg
    Domain: ecommerce.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Template" - Tự động tạo 2 peer (peer0 và peer1)
    # ---------------------------------------------------------------------------
    Template:
      Count: 2 # <-- Số lượng Peer = 2, đúng theo thiết kế HA
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    # "Users" - Tạo 1 user (ngoài Admin)
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
