# organizations/cryptogen/crypto-config-orderer.yaml
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        SANS:
          - localhost
          - orderer0.example.com
          - 127.0.0.1
      - Hostname: orderer1
        SANS:
          - localhost
          - orderer1.example.com
          - 127.0.0.1
      - Hostname: orderer2
        SANS:
          - localhost
          - orderer2.example.com
          - 127.0.0.1
