# ---------------------------------------------------------------------------
# "PeerOrgs" - Định nghĩa tổ chức ShipperOrg (Đơn vị Vận chuyển)
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: ShipperOrg
    Domain: shipper.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Template" - Tự động tạo 2 peer (peer0 và peer1)
    # ---------------------------------------------------------------------------
    Template:
      Count: 2 # <-- Số lượng Peer = 2
      SANS:
        - localhost
    # ---------------------------------------------------------------------------
    # "Users" - Tạo 1 user (ngoài Admin)
    # ---------------------------------------------------------------------------
    Users:
      Count: 1

